import React, { useState, useMemo } from "react";

/**
 * src/pages/EducationFinanciere.jsx
 * Section Éducation financière — Dictionnaire des termes financiers (Québec / Canada).
 * Phase 1 : Retraite & revenus. Chiffres vérifiés pour 2026.
 */

const CATS = [
  "Régimes enregistrés",
  "Rentes publiques",
  "Décaissement & FERR",
  "Concepts retraite",
  "Produits de placement",
  "Risque & rendement",
  "Marchés & frais",
  "Bases de l'impôt",
  "Crédits & déductions",
  "Déclaration & feuillets",
];

const TERMES = [
  { terme: "REER", en: "RRSP — Registered Retirement Savings Plan", cat: "Régimes enregistrés", definition: "Régime enregistré d'épargne-retraite. Compte qui permet de cotiser à l'abri de l'impôt : les cotisations sont déductibles du revenu imposable et les placements croissent sans impôt jusqu'au retrait. Les retraits sont pleinement imposables.", usage: "Pour réduire son impôt pendant les années de revenus élevés et reporter l'imposition à la retraite, quand le taux marginal est généralement plus bas.", exemple: "En 2026, le plafond est de 18 % du revenu gagné de l'année précédente, jusqu'à un maximum de 33 810 $, moins le facteur d'équivalence si vous avez un régime d'employeur.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/reer-fonds-enregistres-revenu-retraite-ferr.html" },
  { terme: "FERR", en: "RRIF — Registered Retirement Income Fund", cat: "Régimes enregistrés", definition: "Fonds enregistré de revenu de retraite. Compte de décaissement issu de la conversion d'un REER : les placements continuent de croître à l'abri de l'impôt, mais un retrait minimum imposable est obligatoire chaque année.", usage: "Pour transformer son épargne REER en revenu de retraite. La conversion du REER en FERR est obligatoire au plus tard à la fin de l'année de vos 71 ans.", exemple: "À 71 ans, le retrait minimum est de 5,28 % de la valeur du FERR au 31 décembre précédent ; à 72 ans, 5,40 %.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/reer-fonds-enregistres-revenu-retraite-ferr/recevoir-paiements-ferr.html" },
  { terme: "CELI", en: "TFSA — Tax-Free Savings Account", cat: "Régimes enregistrés", definition: "Compte d'épargne libre d'impôt. Les cotisations ne sont pas déductibles, mais la croissance et les retraits sont totalement libres d'impôt. Les droits inutilisés se reportent et les retraits se récupèrent l'année suivante.", usage: "Polyvalent : épargne d'urgence, projets, ou complément de retraite non imposable qui n'affecte pas les prestations gouvernementales (PSV, SRG).", exemple: "Le plafond 2026 est de 7 000 $. Une personne admissible depuis 2009 qui n'a jamais cotisé dispose de 109 000 $ de droits cumulés.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/compte-epargne-libre-impot.html" },
  { terme: "CELIAPP", en: "FHSA — First Home Savings Account", cat: "Régimes enregistrés", definition: "Compte d'épargne libre d'impôt pour l'achat d'une première propriété. Combine les avantages du REER (cotisations déductibles) et du CELI (retraits non imposables) lorsque les fonds servent à acheter une première habitation admissible.", usage: "Pour un premier acheteur qui veut bâtir sa mise de fonds. Aucun remboursement requis, contrairement au RAP.", exemple: "Plafond de 8 000 $ par année, jusqu'à 40 000 $ à vie. Cumulable avec le RAP (60 000 $) pour la même propriété.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/compte-epargne-libre-impot-achat-premiere-propriete.html" },
  { terme: "REER de conjoint", en: "Spousal RRSP", cat: "Régimes enregistrés", definition: "REER dont le cotisant est une personne mais le rentier (titulaire) est son conjoint. Le cotisant obtient la déduction, et les retraits futurs sont imposés au nom du conjoint rentier.", usage: "Outil de fractionnement du revenu : équilibrer les revenus de retraite de deux conjoints pour réduire l'impôt total du ménage.", exemple: "Un conjoint à revenu élevé cotise au REER de l'autre, à plus faible revenu, pour que le retrait soit imposé à un taux moindre.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/reer-fonds-enregistres-revenu-retraite-ferr.html" },
  { terme: "RAP", en: "HBP — Home Buyers' Plan", cat: "Régimes enregistrés", definition: "Régime d'accession à la propriété. Permet de retirer des fonds de son REER, sans impôt immédiat, pour acheter ou construire une première habitation admissible.", usage: "Financer une mise de fonds. Le montant retiré doit être remboursé au REER sur 15 ans, sinon la portion non remboursée est ajoutée au revenu imposable.", exemple: "Le plafond de retrait est de 60 000 $ par personne (porté de 35 000 $ à 60 000 $), donc 120 000 $ pour un couple.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/reer-fonds-enregistres-revenu-retraite-ferr/regime-accession-propriete-rap.html" },
  { terme: "REEP", en: "LLP — Lifelong Learning Plan", cat: "Régimes enregistrés", definition: "Régime d'encouragement à l'éducation permanente. Permet de retirer des fonds du REER sans impôt pour financer des études à temps plein, pour soi ou son conjoint.", usage: "Retour aux études financé par le REER. Remboursement requis sur 10 ans.", exemple: "Retrait maximal de 10 000 $ par année, jusqu'à 20 000 $ au total, sur une période maximale de 4 ans.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/reer-fonds-enregistres-revenu-retraite-ferr/regime-encouragement-education-permanente-reep.html" },
  { terme: "REEE", en: "RESP — Registered Education Savings Plan", cat: "Régimes enregistrés", definition: "Régime enregistré d'épargne-études. Compte pour épargner en vue des études postsecondaires d'un enfant, bonifié par des subventions gouvernementales (SCEE fédérale, IQEE québécois).", usage: "Constituer un fonds d'études tout en profitant des subventions. La croissance est imposée au nom de l'étudiant (faible revenu) au moment du retrait.", exemple: "La subvention fédérale (SCEE) ajoute 20 % des cotisations, jusqu'à 500 $ par an et 7 200 $ à vie par enfant ; le Québec (IQEE) ajoute 10 %.", source: "Gouvernement du Canada", url: "https://www.canada.ca/fr/services/prestations/education/epargne-etudes/regime-epargne-etudes.html" },
  { terme: "CRI", en: "LIRA — Locked-In Retirement Account", cat: "Régimes enregistrés", definition: "Compte de retraite immobilisé. Reçoit les sommes provenant d'un régime de pension d'employeur lorsqu'on quitte cet emploi. Les fonds sont « immobilisés » : aucun retrait avant la retraite (sauf exceptions).", usage: "Conserver à l'abri de l'impôt les droits de pension accumulés chez un ancien employeur.", exemple: "Au moment de la retraite, le CRI se transforme en FRV pour générer un revenu, un peu comme le REER se transforme en FERR.", source: "Retraite Québec", url: "https://www.retraitequebec.gouv.qc.ca/fr/Pages/accueil.aspx" },
  { terme: "FRV", en: "LIF — Life Income Fund", cat: "Régimes enregistrés", definition: "Fonds de revenu viager. Compte de décaissement issu d'un CRI ou d'un régime de pension. Comme le FERR, il impose un retrait minimum annuel, mais ajoute aussi un retrait maximum (les fonds restent partiellement immobilisés).", usage: "Tirer un revenu de retraite à partir de droits de pension immobilisés.", exemple: "Contrairement au FERR, le FRV est soumis à un plafond de retrait annuel fixé selon l'âge et un taux de référence.", source: "Retraite Québec", url: "https://www.retraitequebec.gouv.qc.ca/fr/Pages/accueil.aspx" },
  { terme: "RPA", en: "RPP — Registered Pension Plan", cat: "Régimes enregistrés", definition: "Régime de pension agréé. Régime de retraite parrainé par un employeur. Se décline surtout en régime à prestations déterminées (PD) ou à cotisations déterminées (CD).", usage: "Accumuler un revenu de retraite via son emploi. Réduit l'espace REER personnel via le facteur d'équivalence.", exemple: "Un régime PD garantit une rente calculée selon le salaire et les années de service ; un régime CD dépend du rendement des placements accumulés.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/reer-fonds-enregistres-revenu-retraite-ferr.html" },
  { terme: "Régime à prestations déterminées (PD)", en: "Defined Benefit (DB) plan", cat: "Régimes enregistrés", definition: "Type de RPA où la rente de retraite est déterminée d'avance par une formule (souvent salaire moyen × années de service × un pourcentage). C'est l'employeur qui assume le risque de placement.", usage: "Procure un revenu de retraite prévisible et souvent indexé.", exemple: "Formule typique : 2 % × années de service × salaire moyen des 5 meilleures années.", source: "Retraite Québec", url: "https://www.retraitequebec.gouv.qc.ca/fr/Pages/accueil.aspx" },
  { terme: "Régime à cotisations déterminées (CD)", en: "Defined Contribution (DC) plan", cat: "Régimes enregistrés", definition: "Type de RPA où seules les cotisations sont fixées. La rente finale dépend des sommes accumulées et du rendement des placements : c'est le participant qui assume le risque.", usage: "Accumuler un capital de retraite, souvent avec une cotisation égalée par l'employeur.", exemple: "L'employé cotise 5 % de son salaire, l'employeur égale 5 % ; le solde final dépend des marchés.", source: "Retraite Québec", url: "https://www.retraitequebec.gouv.qc.ca/fr/Pages/accueil.aspx" },
  { terme: "RVER", en: "VRSP — Voluntary Retirement Savings Plan", cat: "Régimes enregistrés", definition: "Régime volontaire d'épargne-retraite. Régime collectif que les employeurs québécois sans régime de retraite doivent offrir. L'adhésion de l'employé est automatique, avec possibilité de se retirer.", usage: "Donner accès à l'épargne-retraite par retenue sur la paie aux travailleurs sans régime d'employeur.", exemple: "Les cotisations de l'employé sont déductibles comme un REER ; l'employeur n'est pas obligé d'y cotiser.", source: "Retraite Québec", url: "https://www.retraitequebec.gouv.qc.ca/fr/Pages/accueil.aspx" },
  { terme: "RPDB", en: "DPSP — Deferred Profit Sharing Plan", cat: "Régimes enregistrés", definition: "Régime de participation différée aux bénéfices. Régime par lequel un employeur partage une partie de ses bénéfices avec ses employés, à l'abri de l'impôt jusqu'au retrait.", usage: "Avantage social lié à la performance de l'entreprise ; souvent jumelé à un régime CD.", exemple: "Seul l'employeur peut cotiser ; les sommes sont imposables au moment du retrait par l'employé.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/reer-fonds-enregistres-revenu-retraite-ferr.html" },
  { terme: "RRQ", en: "QPP — Quebec Pension Plan", cat: "Rentes publiques", definition: "Régime de rentes du Québec. Régime public obligatoire qui verse une rente de retraite (ainsi que des prestations d'invalidité et de survivant) financée par les cotisations des travailleurs et employeurs québécois.", usage: "Socle du revenu de retraite. On peut la demander entre 60 et 72 ans ; plus on attend, plus la rente est élevée.", exemple: "Demandée avant 65 ans : réduction de 0,6 % par mois (−36 % à 60 ans). Reportée après 65 ans : bonification de 0,7 % par mois (jusqu'à ~+59 % à 72 ans).", source: "Retraite Québec", url: "https://www.retraitequebec.gouv.qc.ca/fr/Pages/accueil.aspx" },
  { terme: "RPC", en: "CPP — Canada Pension Plan", cat: "Rentes publiques", definition: "Régime de pensions du Canada. Équivalent du RRQ pour les provinces autres que le Québec. Un travailleur ayant cotisé aux deux verra ses droits coordonnés.", usage: "Pertinent pour qui a travaillé hors Québec ; les périodes cotisées au RPC et au RRQ sont combinées au moment de la rente.", exemple: "Une personne ayant travaillé en Ontario puis au Québec accumule des droits dans les deux régimes, versés de façon coordonnée.", source: "Gouvernement du Canada", url: "https://www.canada.ca/fr/services/prestations/pensionspubliques/rpc.html" },
  { terme: "PSV", en: "OAS — Old Age Security", cat: "Rentes publiques", definition: "Pension de la Sécurité de la vieillesse. Prestation fédérale mensuelle imposable versée dès 65 ans, basée sur les années de résidence au Canada et non sur les cotisations de travail.", usage: "Revenu de base à la retraite. Peut être reportée jusqu'à 70 ans (+0,6 %/mois, max +36 %). Sujette à récupération si le revenu est élevé.", exemple: "Montant maximal 2026 : 743,05 $/mois (65-74 ans) et 817,36 $/mois (75 ans et plus).", source: "Gouvernement du Canada", url: "https://www.canada.ca/fr/services/prestations/pensionspubliques/rpc/securite-vieillesse.html" },
  { terme: "Récupération de la PSV", en: "OAS clawback (recovery tax)", cat: "Rentes publiques", definition: "Impôt de récupération qui réduit la PSV lorsque le revenu net dépasse un seuil. On rembourse 15 cents par dollar de revenu excédentaire, jusqu'à élimination complète de la pension.", usage: "Élément clé de la planification du décaissement : gérer son revenu net pour éviter ou minimiser la récupération.", exemple: "En 2026, la récupération débute à 90 997 $ de revenu net et la PSV est entièrement récupérée vers 148 451 $ (65-74 ans).", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/services/prestations/pensionspubliques/rpc/securite-vieillesse/impot-recuperation.html" },
  { terme: "SRG", en: "GIS — Guaranteed Income Supplement", cat: "Rentes publiques", definition: "Supplément de revenu garanti. Prestation fédérale mensuelle non imposable versée aux bénéficiaires de la PSV à faible revenu, âgés de 65 ans et plus.", usage: "Soutien aux aînés à faible revenu. Le montant diminue à mesure que le revenu augmente.", exemple: "Pour une personne seule en 2026, le SRG peut atteindre environ 1 105 $/mois et diminue de 0,50 $ par dollar de revenu additionnel.", source: "Gouvernement du Canada", url: "https://www.canada.ca/fr/services/prestations/pensionspubliques/rpc/securite-vieillesse/supplement-revenu-garanti.html" },
  { terme: "MGA", en: "YMPE — Year's Maximum Pensionable Earnings", cat: "Rentes publiques", definition: "Maximum des gains admissibles. Plafond annuel de revenu de travail sur lequel on cotise au RRQ et qui sert à calculer la rente.", usage: "Sert de base aux cotisations et à la rente du RRQ, ainsi qu'à plusieurs autres paramètres fiscaux.", exemple: "Le MGA est de 74 600 $ en 2026 (hausse de 3 300 $ par rapport à 2025).", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/entreprises/retenues-a-la-source-et-cotisations-de-lemployeur/calcul-des-retenues-et-des-cotisations/cotisations-au-rrq/maximum-des-gains-admissibles-et-taux-de-cotisation/" },
  { terme: "MSGA", en: "YAMPE — Year's Additional Maximum Pensionable Earnings", cat: "Rentes publiques", definition: "Maximum supplémentaire des gains admissibles. Deuxième plafond, introduit en 2024, sur lequel s'applique une cotisation additionnelle dans le cadre de la bonification du RRQ.", usage: "Augmente la rente future des travailleurs à revenu plus élevé via une cotisation supplémentaire.", exemple: "En 2026, le MSGA est de 85 000 $, soit 114 % du MGA ; un taux de 4 % s'applique entre le MGA et le MSGA.", source: "Retraite Québec", url: "https://www.rrq.gouv.qc.ca/fr/programmes/regime_rentes/Pages/regime-supplementaire.aspx" },
  { terme: "Bonification du RRQ", en: "QPP enhancement", cat: "Rentes publiques", definition: "Régime supplémentaire mis en place graduellement depuis 2019. Hausse les cotisations et, à terme, fait passer le taux de remplacement de la rente de 25 % à 33,33 % des gains admissibles.", usage: "Améliore la rente future des plus jeunes travailleurs ; l'effet plein se fera sentir pour les carrières complètes après la réforme.", exemple: "En 2026, le taux de cotisation de base au RRQ est de 12,6 % (partagé employeur/employé) plus 4 % sur la portion entre le MGA et le MSGA.", source: "Retraite Québec", url: "https://www.rrq.gouv.qc.ca/fr/programmes/regime_rentes/Pages/regime-supplementaire.aspx" },
  { terme: "Rente de conjoint survivant", en: "Survivor's pension", cat: "Rentes publiques", definition: "Rente versée par le RRQ au conjoint survivant d'une personne qui a suffisamment cotisé. Le montant dépend de l'âge du survivant et des droits accumulés par la personne décédée.", usage: "Protection du conjoint en cas de décès du cotisant.", exemple: "Le survivant peut recevoir une rente combinée (sa propre rente + une portion de celle du défunt), soumise à un maximum.", source: "Retraite Québec", url: "https://www.retraitequebec.gouv.qc.ca/fr/Pages/accueil.aspx" },
  { terme: "Prestation de décès (RRQ)", en: "QPP death benefit", cat: "Rentes publiques", definition: "Montant forfaitaire unique versé par le RRQ à la succession (ou à la personne ayant payé les funérailles) au décès d'un cotisant admissible.", usage: "Aide à couvrir les frais funéraires.", exemple: "La prestation de décès du RRQ est d'un montant forfaitaire maximal de 2 500 $.", source: "Retraite Québec", url: "https://www.retraitequebec.gouv.qc.ca/fr/Pages/accueil.aspx" },
  { terme: "Décaissement", en: "Decumulation / drawdown", cat: "Décaissement & FERR", definition: "Phase de la retraite où l'on convertit son épargne accumulée en revenu. L'enjeu est l'ordre et le rythme des retraits (REER/FERR, CELI, non enregistré) pour optimiser l'impôt et la durée du capital.", usage: "Établir une stratégie de retraits qui minimise l'impôt à vie et préserve les prestations comme la PSV.", exemple: "Une stratégie courante : décaisser d'abord le non-enregistré et une partie du REER pour « lisser » l'impôt avant 72 ans, en préservant le CELI.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Retrait minimum du FERR", en: "RRIF minimum withdrawal", cat: "Décaissement & FERR", definition: "Pourcentage de la valeur du FERR que la loi oblige à retirer chaque année, à partir de l'année suivant l'ouverture. Le facteur augmente avec l'âge.", usage: "Détermine le revenu imposable plancher tiré du FERR ; on peut toujours retirer davantage.", exemple: "5,28 % à 71 ans, 5,40 % à 72 ans, puis le facteur grimpe pour plafonner à 20 % à 95 ans et plus.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/reer-fonds-enregistres-revenu-retraite-ferr/recevoir-paiements-ferr.html" },
  { terme: "Conversion REER → FERR", en: "RRSP-to-RRIF conversion", cat: "Décaissement & FERR", definition: "Transformation obligatoire du REER en véhicule de revenu (FERR ou rente) au plus tard le 31 décembre de l'année des 71 ans. Aucune nouvelle cotisation n'est ensuite possible dans le FERR.", usage: "Étape charnière de la planification : on peut convertir plus tôt pour profiter du crédit pour revenu de pension et du fractionnement.", exemple: "Une personne qui atteint 71 ans en 2026 doit avoir converti son REER avant la fin de 2026.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/reer-fonds-enregistres-revenu-retraite-ferr.html" },
  { terme: "Rente viagère", en: "Life annuity", cat: "Décaissement & FERR", definition: "Produit d'assurance qui, en échange d'un capital, verse un revenu garanti pour le reste de la vie. Transfère le risque de longévité à l'assureur.", usage: "Sécuriser un revenu de base à vie, en complément des rentes publiques.", exemple: "Convertir une partie de son FERR en rente viagère pour couvrir les dépenses essentielles, peu importe la durée de vie.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Rente certaine", en: "Term-certain annuity", cat: "Décaissement & FERR", definition: "Rente qui verse un revenu pour une période déterminée (par ex. jusqu'à 90 ans) plutôt que pour la vie entière. Si le rentier décède avant la fin, le solde va à la succession.", usage: "Couvrir une période précise ou faire le pont jusqu'au début d'une autre source de revenu.", exemple: "Une rente certaine jusqu'à 65 ans pour combler le revenu entre la fin du travail et le début de la PSV.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Fractionnement du revenu de pension", en: "Pension income splitting", cat: "Décaissement & FERR", definition: "Mécanisme fiscal permettant d'attribuer jusqu'à 50 % de certains revenus de pension admissibles à son conjoint, afin de réduire l'impôt total du couple.", usage: "Équilibrer les revenus imposables des deux conjoints, surtout après 65 ans (le revenu de FERR devient admissible).", exemple: "Un retraité avec 60 000 $ de FERR peut en attribuer 30 000 $ à son conjoint à plus faible revenu, abaissant le taux marginal global.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Crédit pour revenu de pension", en: "Pension income tax credit", cat: "Décaissement & FERR", definition: "Crédit d'impôt non remboursable accordé sur les premiers dollars de revenu de pension admissible (par ex. revenu de FERR ou de rente) à compter de 65 ans.", usage: "Réduire l'impôt sur une tranche de revenu de retraite ; incite à convertir une partie du REER en FERR dès 65 ans.", exemple: "Le crédit fédéral s'applique sur un maximum de 2 000 $ de revenu de pension admissible ; le Québec a son propre montant.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Droits de cotisation", en: "Contribution room", cat: "Concepts retraite", definition: "Montant maximal qu'une personne peut cotiser à un régime (REER, CELI, CELIAPP) une année donnée, incluant les droits inutilisés reportés des années passées.", usage: "Suivre ses droits pour maximiser ses cotisations sans dépasser le plafond (et éviter la pénalité sur cotisation excédentaire).", exemple: "L'avis de cotisation de l'ARC indique vos droits REER ; l'espace CELI se trouve dans Mon dossier.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Facteur d'équivalence (FE)", en: "Pension Adjustment (PA)", cat: "Concepts retraite", definition: "Valeur des droits de pension accumulés dans un régime d'employeur (RPA ou RPDB) au cours d'une année. Il réduit l'espace de cotisation REER de l'année suivante.", usage: "Explique pourquoi un employé avec un bon régime de retraite a peu d'espace REER personnel.", exemple: "Un FE de 12 000 $ réduit d'autant les droits REER que vous pourriez autrement accumuler.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Cotisation excédentaire", en: "Over-contribution", cat: "Concepts retraite", definition: "Somme cotisée au-delà des droits permis dans un REER ou un CELI. Elle entraîne généralement une pénalité fiscale de 1 % par mois sur l'excédent.", usage: "À surveiller, surtout au CELI où un retrait ne libère de l'espace que l'année civile suivante.", exemple: "Recotiser au CELI le montant retiré dans la même année peut créer une cotisation excédentaire taxée à 1 %/mois.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/compte-epargne-libre-impot.html" },
  { terme: "Taux de remplacement du revenu", en: "Income replacement ratio", cat: "Concepts retraite", definition: "Proportion du revenu de travail d'avant la retraite qu'il faut viser comme revenu à la retraite pour maintenir son niveau de vie. Souvent estimé autour de 70 %.", usage: "Point de départ pour fixer un objectif de revenu de retraite et évaluer l'écart à combler par l'épargne.", exemple: "Avec un salaire de 80 000 $, un taux de 70 % vise un revenu de retraite d'environ 56 000 $ par année.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Taux marginal d'imposition", en: "Marginal tax rate", cat: "Concepts retraite", definition: "Taux d'impôt (fédéral + provincial) qui s'applique au prochain dollar de revenu. Au Québec, il est progressif et combine les deux paliers de gouvernement.", usage: "Guide les décisions de cotisation et de retrait : cotiser quand le taux est élevé, retirer quand il est bas.", exemple: "Un retrait REER fait à un taux marginal de 47 % coûte beaucoup plus cher en impôt que le même retrait à 27 %.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Indexation", en: "Indexation", cat: "Concepts retraite", definition: "Ajustement automatique d'un montant (rente, prestation, plafond fiscal) en fonction de l'inflation, afin d'en préserver le pouvoir d'achat.", usage: "Distingue un revenu de retraite qui suit le coût de la vie d'un revenu fixe qui s'érode avec le temps.", exemple: "Le RRQ et la PSV sont indexés ; une rente d'employeur peut l'être en tout, en partie, ou pas du tout.", source: "Retraite Québec", url: "https://www.retraitequebec.gouv.qc.ca/fr/Pages/accueil.aspx" },
  { terme: "Espérance de vie", en: "Life expectancy", cat: "Concepts retraite", definition: "Nombre moyen d'années qu'une personne d'un âge donné peut espérer vivre. En planification, on utilise souvent un horizon prudent (90-95 ans) pour réduire le risque d'épuiser son capital.", usage: "Détermine la durée sur laquelle le capital de retraite doit durer.", exemple: "Pour un couple de 65 ans, il y a une probabilité élevée qu'au moins un conjoint atteigne 90 ans, d'où une projection prudente.", source: "Institut de planification financière", url: "https://institutpf.org/" },
  { terme: "Inflation", en: "Inflation", cat: "Concepts retraite", definition: "Hausse générale et soutenue des prix qui réduit le pouvoir d'achat de l'argent au fil du temps. Paramètre central de toute projection de retraite.", usage: "Justifie d'investir pour une croissance supérieure à l'inflation et d'indexer ses objectifs de revenu.", exemple: "À 2 % d'inflation, un panier de 50 000 $ aujourd'hui coûtera environ 74 000 $ dans 20 ans.", source: "Institut de planification financière", url: "https://institutpf.org/" },
  { terme: "NIF", en: "Required retirement capital (MonPlanFin)", cat: "Concepts retraite", definition: "Indicateur de MonPlanFin représentant le capital nécessaire pour soutenir l'objectif de revenu à la retraite, une fois retranchées les rentes garanties (RRQ, PSV, régimes d'employeur).", usage: "Comparer le capital requis au capital projeté pour mesurer l'écart à combler.", exemple: "Si l'objectif est de 56 000 $/an et que les rentes garanties couvrent 26 000 $, le NIF capitalise le manque annuel de 30 000 $.", source: "MonPlanFin (méthodologie IQPF)", url: "https://institutpf.org/" },
  { terme: "Action", en: "Common share / Stock", cat: "Produits de placement", definition: "Titre de propriété représentant une fraction d'une entreprise. Le détenteur participe aux bénéfices (dividendes) et à la variation de valeur du titre, sans garantie de rendement ni de capital.", usage: "Viser la croissance à long terme; convient à un horizon long et à une tolérance au risque plus élevée.", exemple: "Acheter l'action d'une banque canadienne procure des dividendes trimestriels et une plus-value si le cours monte.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Action privilégiée", en: "Preferred share", cat: "Produits de placement", definition: "Action qui verse généralement un dividende fixe et prioritaire par rapport aux actions ordinaires, mais qui ne donne habituellement pas de droit de vote.", usage: "Rechercher un revenu de dividende plus stable, à mi-chemin entre l'action ordinaire et l'obligation.", exemple: "Une action privilégiée à 5 % verse son dividende avant tout versement aux actionnaires ordinaires.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Obligation", en: "Bond", cat: "Produits de placement", definition: "Titre de créance : on prête de l'argent à un émetteur (gouvernement ou entreprise) qui verse des intérêts (coupons) et rembourse le capital à l'échéance.", usage: "Apporter de la stabilité et un revenu au portefeuille; généralement moins risqué que les actions.", exemple: "Une obligation de 10 000 $ à 4 % verse 400 $ d'intérêt par an jusqu'au remboursement à l'échéance.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "FNB", en: "ETF — Exchange-Traded Fund", cat: "Produits de placement", definition: "Fonds négocié en bourse. Panier de titres qui se négocie comme une action. Souvent indiciel et à faibles frais.", usage: "Obtenir une diversification instantanée à faible coût, en un seul achat.", exemple: "Un FNB qui suit le S&P/TSX donne une exposition aux grandes entreprises canadiennes en une transaction.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Fonds commun de placement", en: "Mutual fund", cat: "Produits de placement", definition: "Placement collectif géré par un professionnel : les épargnants achètent des parts d'un portefeuille diversifié. Les frais (RFG) sont souvent plus élevés que ceux d'un FNB.", usage: "Déléguer la gestion et diversifier avec de petits montants, souvent par prélèvements automatiques.", exemple: "Un fonds équilibré détient un mélange d'actions et d'obligations géré pour vous.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Fonds indiciel", en: "Index fund", cat: "Produits de placement", definition: "Fonds (FNB ou commun) qui reproduit un indice de référence plutôt que de tenter de le battre. Gestion passive et frais généralement très bas.", usage: "Capter le rendement moyen du marché à faible coût, sur le long terme.", exemple: "Un fonds indiciel S&P 500 réplique la performance des 500 grandes sociétés américaines.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "CPG", en: "GIC — Guaranteed Investment Certificate", cat: "Produits de placement", definition: "Certificat de placement garanti. Le capital est garanti et un taux d'intérêt fixe est versé sur une durée déterminée. Faible risque, faible rendement.", usage: "Sécuriser une somme dont on aura besoin à une date connue, sans risque de perte.", exemple: "Un CPG de 2 ans à 4 % garantit le capital et l'intérêt à l'échéance.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Fonds distinct", en: "Segregated fund", cat: "Produits de placement", definition: "Fonds offert par un assureur, assorti de garanties (du capital au décès ou à l'échéance) et d'avantages successoraux (désignation de bénéficiaire). Les frais sont plus élevés.", usage: "Combiner placement et protection d'assurance, avec transmission rapide au décès.", exemple: "Un fonds distinct peut garantir de 75 % à 100 % du capital investi à l'échéance.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Bon du Trésor", en: "Treasury bill (T-bill)", cat: "Produits de placement", definition: "Titre de dette à court terme émis par un gouvernement, vendu à escompte et remboursé à pleine valeur à l'échéance. Très sûr et liquide.", usage: "Placer des liquidités à court terme avec un risque minimal.", exemple: "Un bon acheté 98 $ et remboursé 100 $ dans 3 mois procure un intérêt implicite.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "FPI", en: "REIT — Real Estate Investment Trust", cat: "Produits de placement", definition: "Fiducie de placement immobilier. Permet d'investir dans un portefeuille d'immeubles (revenus de loyers) en achetant un titre coté en bourse, sans posséder de propriété directement.", usage: "Obtenir une exposition à l'immobilier et un revenu, avec la liquidité d'un titre boursier.", exemple: "Une FPI de centres commerciaux distribue une partie des loyers perçus à ses porteurs de parts.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Cryptoactif", en: "Crypto-asset", cat: "Produits de placement", definition: "Actif numérique (ex. Bitcoin) reposant sur la chaîne de blocs. Non garanti, très volatil et faiblement encadré comparé aux placements traditionnels.", usage: "Spéculatif; ne devrait représenter qu'une très petite portion d'un portefeuille, s'il y figure.", exemple: "La valeur d'un cryptoactif peut varier de dizaines de pour cent en quelques jours.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Rendement", en: "Return", cat: "Risque & rendement", definition: "Gain ou perte d'un placement sur une période, exprimé en pourcentage. Il combine la variation de valeur et les revenus reçus (intérêts, dividendes).", usage: "Mesurer la performance et comparer des placements entre eux.", exemple: "Un placement passé de 1 000 $ à 1 070 $ en un an a un rendement de 7 %.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Risque", en: "Risk", cat: "Risque & rendement", definition: "Possibilité que le rendement réel diffère du rendement attendu, y compris la perte d'une partie du capital. En général, plus le rendement potentiel est élevé, plus le risque l'est aussi.", usage: "Choisir des placements alignés sur sa tolérance et son horizon.", exemple: "Les actions offrent un rendement potentiel plus élevé que les CPG, mais avec un risque de perte plus grand.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Volatilité", en: "Volatility", cat: "Risque & rendement", definition: "Ampleur des fluctuations de la valeur d'un placement dans le temps. Une forte volatilité signifie des hausses et des baisses plus marquées.", usage: "Évaluer le confort psychologique et l'horizon nécessaire pour un placement.", exemple: "Un fonds d'actions technologiques est typiquement plus volatil qu'un fonds d'obligations.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Diversification", en: "Diversification", cat: "Risque & rendement", definition: "Répartir ses placements entre plusieurs titres, secteurs et régions afin de réduire le risque global. Les pertes des uns sont compensées par les gains des autres.", usage: "Réduire l'impact d'un mauvais placement sur l'ensemble du portefeuille.", exemple: "Ne pas mettre tous ses œufs dans le même panier : détenir des milliers d'entreprises via un FNB mondial.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Répartition de l'actif", en: "Asset allocation", cat: "Risque & rendement", definition: "Façon de répartir un portefeuille entre les grandes catégories d'actifs (actions, obligations, liquidités) selon l'objectif, l'horizon et la tolérance au risque.", usage: "Premier déterminant du rendement et du risque d'un portefeuille à long terme.", exemple: "Un profil équilibré pourrait viser 60 % d'actions et 40 % d'obligations.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Tolérance au risque", en: "Risk tolerance", cat: "Risque & rendement", definition: "Capacité et volonté d'un investisseur à supporter les baisses de valeur de ses placements. Elle détermine le profil d'investisseur, du plus prudent au plus audacieux.", usage: "Établie au moyen d'un questionnaire; elle guide le choix de la répartition de l'actif.", exemple: "Un investisseur prudent dormira mal avec 80 % d'actions et privilégiera plus d'obligations.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Horizon de placement", en: "Time horizon", cat: "Risque & rendement", definition: "Durée pendant laquelle on prévoit conserver un placement avant d'avoir besoin des fonds. Plus l'horizon est long, plus on peut tolérer la volatilité.", usage: "Aligner le niveau de risque sur le moment où l'argent sera utilisé.", exemple: "Pour un achat dans 1 an, on privilégie un CPG; pour la retraite dans 25 ans, des actions.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Intérêts composés", en: "Compound interest", cat: "Risque & rendement", definition: "Intérêts qui s'ajoutent au capital et génèrent à leur tour des intérêts. L'effet boule de neige s'accentue fortement avec le temps.", usage: "Argument central pour commencer à épargner tôt et réinvestir les revenus.", exemple: "À 7 %, un placement double environ tous les 10 ans grâce aux intérêts composés.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Rééquilibrage", en: "Rebalancing", cat: "Risque & rendement", definition: "Ramener périodiquement le portefeuille à sa répartition cible en vendant ce qui a trop monté et en achetant ce qui a baissé.", usage: "Maintenir le niveau de risque voulu et discipliner ses décisions.", exemple: "Si les actions passent de 60 % à 70 % du portefeuille, on en vend pour revenir à 60 %.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Achats périodiques par sommes fixes", en: "Dollar-cost averaging", cat: "Risque & rendement", definition: "Investir un montant fixe à intervalles réguliers, peu importe l'état du marché. On achète plus de parts quand les prix sont bas, moins quand ils sont hauts.", usage: "Réduire l'impact du moment d'entrée et automatiser l'épargne.", exemple: "Investir 300 $ par mois dans un FNB, beau temps mauvais temps.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Rendement réel", en: "Real return", cat: "Risque & rendement", definition: "Rendement d'un placement après avoir retranché l'inflation. Il mesure la véritable croissance du pouvoir d'achat.", usage: "Évaluer si un placement fait réellement croître la richesse une fois l'inflation prise en compte.", exemple: "Un rendement de 5 % avec une inflation de 2 % donne un rendement réel d'environ 3 %.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Liquidité", en: "Liquidity", cat: "Risque & rendement", definition: "Facilité à convertir un placement en argent rapidement et sans perte de valeur importante.", usage: "S'assurer d'avoir accès à des fonds en cas de besoin imprévu.", exemple: "Une action cotée est très liquide; un immeuble l'est beaucoup moins.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "RFG", en: "MER — Management Expense Ratio", cat: "Marchés & frais", definition: "Ratio des frais de gestion. Pourcentage annuel prélevé sur l'actif d'un fonds pour couvrir sa gestion et son administration. Il réduit directement le rendement obtenu.", usage: "Comparer le coût des fonds; un RFG élevé gruge le rendement à long terme.", exemple: "Un RFG de 2 % coûte 2 000 $ par an sur 100 000 $ investis.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Frais d'acquisition et de rachat", en: "Sales and redemption fees (loads)", cat: "Marchés & frais", definition: "Commissions payées à l'achat (frais d'acquisition) ou à la vente (frais de rachat) de certains fonds. Distincts du RFG, prélevé en continu.", usage: "Vérifier la structure de frais avant d'acheter un fonds.", exemple: "Un fonds à frais de rachat dégressifs pénalise une vente dans les premières années.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Dividende", en: "Dividend", cat: "Marchés & frais", definition: "Part des bénéfices d'une entreprise versée à ses actionnaires. Au Canada, les dividendes déterminés de sociétés canadiennes donnent droit à un crédit d'impôt.", usage: "Source de revenu et de rendement, fiscalement avantageuse hors des comptes enregistrés.", exemple: "Une action versant 4 $ par an sur un cours de 100 $ offre un rendement en dividende de 4 %.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Gain en capital", en: "Capital gain", cat: "Marchés & frais", definition: "Profit réalisé lorsqu'on vend un placement plus cher qu'on l'a payé. Au Canada, 50 % du gain est imposable (taux d'inclusion).", usage: "Type de revenu le plus avantageux fiscalement; à planifier au moment de vendre.", exemple: "Un gain de 10 000 $ ajoute 5 000 $ au revenu imposable (50 % d'inclusion en 2026).", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Revenu d'intérêt", en: "Interest income", cat: "Marchés & frais", definition: "Revenu tiré d'obligations, de CPG ou de comptes d'épargne. Contrairement aux dividendes et aux gains en capital, il est pleinement imposable.", usage: "À loger de préférence dans un compte enregistré (REER, CELI) pour éviter l'impôt annuel.", exemple: "1 000 $ d'intérêt de CPG s'ajoutent en totalité au revenu imposable.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Indice boursier", en: "Stock index", cat: "Marchés & frais", definition: "Panier de titres qui sert de baromètre de la performance d'un marché ou d'un secteur.", usage: "Comparer le rendement d'un portefeuille à celui du marché (sa référence).", exemple: "Le S&P/TSX suit les grandes entreprises canadiennes; le S&P 500, les grandes américaines.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Marché haussier et baissier", en: "Bull and bear market", cat: "Marchés & frais", definition: "Marché haussier : période prolongée de hausse des cours. Marché baissier : recul d'au moins 20 % par rapport à un sommet récent.", usage: "Garder le cap : les marchés baissiers font partie du cycle normal des placements.", exemple: "Après un marché baissier, les marchés ont historiquement fini par se redresser.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Capitalisation boursière", en: "Market capitalization", cat: "Marchés & frais", definition: "Valeur totale d'une entreprise en bourse : le cours de l'action multiplié par le nombre d'actions en circulation.", usage: "Classer les entreprises (grande, moyenne, petite capitalisation) et calibrer le risque.", exemple: "Une société à 50 $ l'action avec 100 millions d'actions vaut 5 milliards en bourse.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Ratio cours/bénéfice (C/B)", en: "Price-to-earnings (P/E) ratio", cat: "Marchés & frais", definition: "Cours de l'action divisé par le bénéfice par action. Il indique combien on paie pour chaque dollar de bénéfice et aide à juger si un titre est cher.", usage: "Comparer la valorisation d'entreprises d'un même secteur.", exemple: "Un C/B de 20 signifie qu'on paie 20 $ pour 1 $ de bénéfice annuel.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Valeur liquidative (VL)", en: "NAV — Net Asset Value", cat: "Marchés & frais", definition: "Valeur d'une part de fonds, soit l'actif net du fonds divisé par le nombre de parts. Elle est recalculée chaque jour de Bourse.", usage: "Prix auquel on achète ou vend des parts d'un fonds commun.", exemple: "Un fonds de 10 millions $ d'actif net réparti en 1 million de parts a une VL de 10 $.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "Gestion active et passive", en: "Active vs passive management", cat: "Marchés & frais", definition: "Gestion active : un gestionnaire tente de battre le marché par sa sélection de titres (frais plus élevés). Gestion passive : on réplique un indice à faibles frais.", usage: "Choix fondamental qui influence les frais et, souvent, le rendement net.", exemple: "Sur de longues périodes, peu de fonds actifs battent leur indice après frais.", source: "Autorité des marchés financiers (AMF)", url: "https://lautorite.qc.ca/grand-public" },
  { terme: "OCRI", en: "CIRO — Canadian Investment Regulatory Organization", cat: "Marchés & frais", definition: "Organisme canadien de réglementation des investissements. Encadre les courtiers en placement et en fonds communs partout au Canada. Né de la fusion de l'OCRCVM (IIROC) et de l'ACFM en 2023.", usage: "Vérifier qu'un courtier ou un représentant est inscrit et encadré.", exemple: "On peut confirmer l'inscription d'une firme auprès de l'OCRI avant d'investir.", source: "Organisme canadien de réglementation des investissements (OCRI)", url: "https://www.ocri.ca/" },
  { terme: "Compte non enregistré", en: "Non-registered account", cat: "Marchés & frais", definition: "Compte de placement ordinaire, sans avantage fiscal particulier. Les revenus (intérêts, dividendes) et les gains en capital y sont imposables chaque année.", usage: "Utilisé une fois les REER, CELI et CELIAPP maximisés.", exemple: "Un gain réalisé dans un compte non enregistré déclenche un impôt l'année de la vente.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Revenu imposable", en: "Taxable income", cat: "Bases de l'impôt", definition: "Revenu total une fois retranchées les déductions admissibles. C'est sur ce montant, et non sur le revenu brut, que l'impôt est calculé.", usage: "Point de départ du calcul de l'impôt; le réduire (ex. par une cotisation REER) abaisse l'impôt.", exemple: "Un revenu brut de 80 000 $ moins 10 000 $ de REER donne un revenu imposable de 70 000 $.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Taux moyen d'imposition", en: "Average tax rate", cat: "Bases de l'impôt", definition: "Pourcentage réel de l'ensemble du revenu payé en impôt, soit l'impôt total divisé par le revenu. Il est toujours inférieur au taux marginal.", usage: "Mesurer le fardeau fiscal global, contrairement au taux marginal qui ne vise que le dernier dollar.", exemple: "Payer 15 000 $ d'impôt sur 70 000 $ de revenu donne un taux moyen d'environ 21 %.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Palier d'imposition", en: "Tax bracket", cat: "Bases de l'impôt", definition: "Tranche de revenu imposée à un taux donné. Le Canada et le Québec ont des taux progressifs : chaque tranche supplémentaire est imposée à un taux plus élevé.", usage: "Comprendre qu'une hausse de revenu n'impose pas tout le revenu au taux supérieur, seulement la tranche concernée.", exemple: "En 2026, le premier palier fédéral est de 14 % et le premier palier québécois de 14 %.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/declaration-de-revenus/produire-votre-declaration-de-revenus/taux-dimposition/" },
  { terme: "Montant personnel de base", en: "Basic personal amount", cat: "Bases de l'impôt", definition: "Tranche de revenu sur laquelle on ne paie pas d'impôt, accordée à tous sous forme de crédit non remboursable.", usage: "Premier allègement fiscal automatique pour chaque contribuable.", exemple: "En 2026 : 16 452 $ au fédéral et 18 952 $ au Québec.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Impôt à deux paliers de gouvernement", en: "Federal and Quebec taxation", cat: "Bases de l'impôt", definition: "Au Québec, l'impôt sur le revenu est perçu par deux gouvernements : le fédéral (ARC) et le provincial (Revenu Québec), chacun avec ses propres taux.", usage: "Explique pourquoi les Québécois produisent deux déclarations et additionnent deux impôts.", exemple: "Le premier taux fédéral est de 14 % en 2026 (réduit de 15 %), auquel s'ajoute l'impôt du Québec.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Abattement du Québec", en: "Quebec abatement", cat: "Bases de l'impôt", definition: "Réduction de 16,5 % de l'impôt fédéral de base accordée aux résidents du Québec, parce que la province administre elle-même certains programmes.", usage: "Évite une double imposition pour les programmes gérés par le Québec.", exemple: "L'impôt fédéral d'un Québécois est réduit de 16,5 % avant l'application des crédits.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "TPS et TVQ", en: "GST and QST", cat: "Bases de l'impôt", definition: "Taxes à la consommation : la TPS fédérale de 5 % et la TVQ québécoise de 9,975 %, pour environ 14,975 % au total sur la plupart des biens et services.", usage: "Taxes payées à l'achat; certains produits essentiels en sont exemptés.", exemple: "Un achat de 100 $ coûte environ 114,98 $ taxes incluses.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Revenu net", en: "Net income", cat: "Bases de l'impôt", definition: "Revenu après certaines déductions. Il sert de base au calcul de plusieurs prestations et de la récupération de la PSV.", usage: "Surveiller son revenu net pour préserver les prestations fondées sur le revenu.", exemple: "Un revenu net élevé peut déclencher la récupération de la PSV à compter de 90 997 $ en 2026.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Cotisations sociales (RRQ, AE, RQAP)", en: "Payroll contributions", cat: "Bases de l'impôt", definition: "Retenues obligatoires sur le salaire : RRQ (retraite), assurance-emploi (AE) et Régime québécois d'assurance parentale (RQAP).", usage: "Financent des programmes sociaux et donnent droit à des prestations.", exemple: "Les cotisations au RRQ et à l'AE apparaissent sur chaque paie et sur le T4 / Relevé 1.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Déduction fiscale", en: "Tax deduction", cat: "Crédits & déductions", definition: "Montant soustrait du revenu avant le calcul de l'impôt. Sa valeur dépend du taux marginal : plus le revenu est élevé, plus l'économie est grande.", usage: "Réduire le revenu imposable (ex. cotisation REER, frais de garde).", exemple: "Une déduction de 1 000 $ à un taux marginal de 40 % économise 400 $ d'impôt.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Crédit d'impôt non remboursable", en: "Non-refundable tax credit", cat: "Crédits & déductions", definition: "Crédit qui réduit l'impôt à payer mais ne peut le rendre négatif : aucun remboursement au-delà de zéro.", usage: "Diminuer l'impôt dû; les crédits inutilisés sont parfois transférables ou reportables.", exemple: "Le montant personnel de base et le crédit pour frais de scolarité sont non remboursables.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Crédit d'impôt remboursable", en: "Refundable tax credit", cat: "Crédits & déductions", definition: "Crédit versé même si l'on ne paie pas d'impôt; il peut générer un remboursement.", usage: "Soutien aux ménages à revenu faible ou moyen, peu importe l'impôt payé.", exemple: "Le crédit d'impôt pour solidarité du Québec est remboursable.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Crédit d'impôt pour dividendes", en: "Dividend tax credit", cat: "Crédits & déductions", definition: "Crédit qui compense l'impôt déjà payé par l'entreprise sur ses bénéfices, ce qui rend les dividendes de sociétés canadiennes avantageux.", usage: "Réduit le taux d'impôt effectif sur les dividendes hors comptes enregistrés.", exemple: "Grâce au crédit, un dividende déterminé est moins imposé qu'un même montant d'intérêt.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Majoration du dividende", en: "Dividend gross-up", cat: "Crédits & déductions", definition: "Mécanisme par lequel le dividende est majoré dans la déclaration de revenus avant l'application du crédit d'impôt pour dividendes.", usage: "Reflète le bénéfice avant impôt de l'entreprise pour calculer correctement le crédit.", exemple: "Un dividende déterminé est majoré de 38 % avant le calcul de l'impôt et du crédit.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Perte en capital", en: "Capital loss", cat: "Crédits & déductions", definition: "Perte réalisée en vendant un placement moins cher qu'on l'a payé. Elle ne peut servir qu'à annuler des gains en capital (50 % d'inclusion).", usage: "Réduire l'impôt sur des gains en capital de l'année, des 3 années passées ou des années futures.", exemple: "Une perte de 5 000 $ peut effacer un gain de 5 000 $ réalisé ailleurs.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Crédit pour frais médicaux", en: "Medical expense credit", cat: "Crédits & déductions", definition: "Crédit pour les frais médicaux admissibles qui dépassent un seuil lié au revenu.", usage: "Récupérer une partie des frais de santé non couverts.", exemple: "Lunettes, soins dentaires et médicaments admissibles peuvent donner droit au crédit.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Crédit pour dons de bienfaisance", en: "Charitable donation credit", cat: "Crédits & déductions", definition: "Crédit pour les dons à des organismes de bienfaisance enregistrés. Le taux est plus avantageux sur la portion des dons dépassant 200 $.", usage: "Réduire l'impôt tout en soutenant une cause; les dons d'un couple peuvent être regroupés.", exemple: "300 $ de dons donnent un crédit plus élevé sur les 100 $ excédant 200 $.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Crédit pour frais de scolarité", en: "Tuition tax credit", cat: "Crédits & déductions", definition: "Crédit non remboursable pour les droits de scolarité postsecondaires. Les montants inutilisés peuvent être reportés ou, au fédéral, transférés à un parent.", usage: "Réduire l'impôt de l'étudiant ou d'un proche qui le soutient.", exemple: "Un étudiant sans impôt à payer reporte ses frais de scolarité à une année future.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Déduction pour frais de garde d'enfants", en: "Child care expense deduction", cat: "Crédits & déductions", definition: "Déduction des frais de garde admissibles engagés pour permettre aux parents de travailler ou d'étudier.", usage: "Réduire le revenu imposable, généralement par le parent au plus faible revenu.", exemple: "Les frais d'une garderie non subventionnée peuvent être déduits dans les limites prévues.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Crédit d'impôt pour solidarité", en: "Quebec solidarity tax credit", cat: "Crédits & déductions", definition: "Crédit remboursable québécois à trois volets (TVQ, logement, villages nordiques) versé aux ménages à revenu faible ou moyen.", usage: "Soutien au coût de la vie; il faut produire sa déclaration pour le recevoir.", exemple: "Le crédit est versé mensuellement ou trimestriellement selon le montant.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Allocation canadienne pour enfants (ACE)", en: "Canada Child Benefit (CCB)", cat: "Crédits & déductions", definition: "Versement mensuel non imposable aux familles, calculé selon le revenu, pour les enfants de moins de 18 ans.", usage: "Aide au coût de l'éducation des enfants; le montant diminue à mesure que le revenu augmente.", exemple: "Une famille à faible revenu reçoit l'ACE maximale par enfant chaque mois.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Crédit pour la TPS/TVH", en: "GST/HST credit", cat: "Crédits & déductions", definition: "Versement trimestriel non imposable destiné à compenser une partie des taxes de vente payées par les ménages à faible revenu.", usage: "Automatique au moment de produire sa déclaration, si on y est admissible.", exemple: "Une personne seule à faible revenu reçoit le crédit TPS/TVH quatre fois par an.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Abri fiscal et report d'impôt", en: "Tax shelter and deferral", cat: "Crédits & déductions", definition: "Stratégies qui reportent l'impôt à plus tard (ex. REER) ou le réduisent légalement. À distinguer des abris fiscaux abusifs, contestés par le fisc.", usage: "Optimiser l'impôt à vie en déplaçant le revenu imposable vers des années à plus faible taux.", exemple: "Le REER reporte l'impôt jusqu'au retrait, souvent à un taux moindre à la retraite.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Exonération cumulative des gains en capital", en: "Lifetime Capital Gains Exemption (LCGE)", cat: "Crédits & déductions", definition: "Exonère un montant à vie de gains en capital réalisés sur des actions admissibles de petite entreprise ou des biens agricoles et de pêche.", usage: "Avantage majeur pour les propriétaires d'entreprise au moment de vendre.", exemple: "Le plafond est de 1,25 M$ depuis le 25 juin 2024.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Fractionnement du revenu", en: "Income splitting", cat: "Crédits & déductions", definition: "Déplacer du revenu vers un membre de la famille imposé à un taux plus bas, dans les limites permises par la loi (ex. REER de conjoint, fractionnement de pension).", usage: "Réduire l'impôt total d'un couple ou d'une famille.", exemple: "Attribuer une partie d'un revenu de FERR à son conjoint après 65 ans.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Impôt minimum de remplacement (IMR)", en: "Alternative Minimum Tax (AMT)", cat: "Crédits & déductions", definition: "Calcul d'impôt parallèle qui limite l'effet de certains avantages fiscaux pour les hauts revenus. On paie le plus élevé entre l'impôt ordinaire et l'IMR.", usage: "À surveiller lors d'années à gains en capital ou à dons importants.", exemple: "Une grande vente d'actions une seule année peut déclencher l'IMR.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Frais de bureau à domicile", en: "Home office expenses", cat: "Crédits & déductions", definition: "Déduction d'une part des frais (loyer, électricité, fournitures) liés à un espace de travail à domicile, sous certaines conditions.", usage: "Utile pour les travailleurs autonomes et certains employés.", exemple: "Un travailleur autonome déduit la portion de son loyer correspondant à son bureau.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Déclaration de revenus", en: "Tax return", cat: "Déclaration & feuillets", definition: "Document annuel déclarant ses revenus et déductions. Particularité du Québec : on produit deux déclarations, une fédérale (ARC) et une provinciale (Revenu Québec).", usage: "Obligatoire chaque printemps; sert aussi à toucher crédits et prestations.", exemple: "La date limite est généralement le 30 avril pour la plupart des contribuables.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Avis de cotisation", en: "Notice of assessment", cat: "Déclaration & feuillets", definition: "Document que l'administration fiscale envoie après le traitement de la déclaration. Il confirme le résultat et indique notamment les droits de cotisation REER.", usage: "Vérifier le calcul du fisc et connaître son espace REER de l'année.", exemple: "L'avis de cotisation indique un remboursement, un solde dû et vos droits REER.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Acompte provisionnel", en: "Tax instalment", cat: "Déclaration & feuillets", definition: "Versements d'impôt faits en cours d'année, exigés de ceux dont l'impôt non retenu à la source dépasse un seuil.", usage: "Concerne souvent les travailleurs autonomes et les retraités à revenus multiples.", exemple: "Un retraité peut devoir verser des acomptes trimestriels sur ses revenus de FERR.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Retenue à la source", en: "Source deduction (withholding)", cat: "Déclaration & feuillets", definition: "Impôt et cotisations prélevés directement sur la paie ou la pension par le payeur, puis remis aux gouvernements.", usage: "Étale le paiement de l'impôt sur l'année; on peut ajuster les retenues.", exemple: "Demander une retenue supplémentaire sur un retrait de FERR pour éviter un solde à payer.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Feuillet T4 et Relevé 1", en: "T4 and RL-1 slips", cat: "Déclaration & feuillets", definition: "Feuillets remis par l'employeur indiquant le salaire et les retenues : T4 au fédéral, Relevé 1 au Québec.", usage: "Documents de base pour produire sa déclaration d'emploi.", exemple: "On reçoit son T4 et son Relevé 1 au plus tard à la fin de février.", source: "Revenu Québec", url: "https://www.revenuquebec.ca/fr/citoyens/" },
  { terme: "Feuillet T5 et Relevé 3", en: "T5 and RL-3 slips", cat: "Déclaration & feuillets", definition: "Feuillets déclarant les revenus de placement (intérêts, dividendes) : T5 au fédéral, Relevé 3 au Québec.", usage: "Servent à déclarer les revenus d'un compte non enregistré.", exemple: "Une institution émet un T5 pour les intérêts versés sur un CPG.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Feuillet T4A et Relevé 2", en: "T4A and RL-2 slips", cat: "Déclaration & feuillets", definition: "Feuillets déclarant les revenus de pension et de retraite (FERR, rente, RPA) : T4A au fédéral, Relevé 2 au Québec.", usage: "Essentiels pour déclarer les revenus de retraite.", exemple: "Un retrait de FERR génère un T4A et un Relevé 2.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
  { terme: "Évitement et évasion fiscale", en: "Tax avoidance vs evasion", cat: "Déclaration & feuillets", definition: "L'évitement utilise des moyens légaux pour réduire l'impôt; l'évasion est illégale (dissimuler des revenus ou gonfler des dépenses).", usage: "Distinguer une planification fiscale légitime d'une fraude.", exemple: "Cotiser au REER est de l'optimisation; cacher un revenu est de l'évasion.", source: "Agence du revenu du Canada (ARC)", url: "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers.html" },
];

const C = {
  gold: "#C9A063",
  text: "rgba(255,255,255,0.92)",
  dim: "rgba(255,255,255,0.55)",
  faint: "rgba(255,255,255,0.4)",
  cardBg: "rgba(255,255,255,0.04)",
  cardBorder: "1px solid rgba(255,255,255,0.08)",
  goldBg: "rgba(201,160,99,0.08)",
  goldBorder: "1px solid rgba(201,160,99,0.30)",
  mono: "var(--font-mono, ui-monospace, monospace)",
};

function TermCard({ t, open, onToggle }) {
  return (
    <div style={{ background: open ? C.goldBg : C.cardBg, border: open ? C.goldBorder : C.cardBorder, borderRadius: 14, padding: "16px 18px", marginBottom: 10, cursor: "pointer", transition: "all .15s ease" }} onClick={onToggle}>
      <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: 12 }}>
        <div>
          <span style={{ fontSize: 16, fontWeight: 700, color: C.text }}>{t.terme}</span>
          <span style={{ fontSize: 12, color: C.faint, marginLeft: 10, fontFamily: C.mono }}>{t.en}</span>
        </div>
        <span style={{ fontSize: 11, color: C.gold, fontWeight: 600, whiteSpace: "nowrap" }}>{t.cat}</span>
      </div>
      {open && (
        <div style={{ marginTop: 12, color: C.dim, fontSize: 13.5, lineHeight: 1.6 }}>
          <p style={{ margin: "0 0 10px", color: C.text }}>{t.definition}</p>
          <p style={{ margin: "0 0 6px" }}><span style={{ color: C.gold, fontWeight: 600 }}>Quand l'utilise-t-on ? </span>{t.usage}</p>
          <p style={{ margin: "0 0 10px" }}><span style={{ color: C.gold, fontWeight: 600 }}>Exemple. </span>{t.exemple}</p>
          <p style={{ margin: 0, fontSize: 11.5, color: C.faint }}>Source : {t.source}{t.url ? (<a href={t.url} target="_blank" rel="noopener noreferrer" style={{ color: C.gold, marginLeft: 6 }}>lien</a>) : null}</p>
        </div>
      )}
    </div>
  );
}

export default function EducationFinanciere() {
  const [q, setQ] = useState("");
  const [cat, setCat] = useState("Toutes");
  const [openKey, setOpenKey] = useState(null);
  const filtres = useMemo(() => {
    const needle = q.trim().toLowerCase();
    return TERMES.filter((t) => {
      const okCat = cat === "Toutes" || t.cat === cat;
      const okQ = !needle || t.terme.toLowerCase().includes(needle) || (t.en || "").toLowerCase().includes(needle) || t.definition.toLowerCase().includes(needle);
      return okCat && okQ;
    });
  }, [q, cat]);
  return (
    <div style={{ maxWidth: 920, margin: "0 auto", padding: "28px 20px 60px", color: C.text }}>
      <p style={{ fontSize: 11, letterSpacing: ".12em", textTransform: "uppercase", color: C.faint, margin: 0 }}>Éducation financière</p>
      <h1 style={{ fontSize: 28, fontWeight: 800, margin: "6px 0 6px" }}>Dictionnaire financier</h1>
      <p style={{ color: C.dim, fontSize: 14, lineHeight: 1.6, margin: "0 0 20px" }}>Les termes financiers du Québec et du Canada, expliqués simplement, avec leur usage courant et des exemples. Retraite, revenus et placements. Chiffres à jour pour 2026.</p>
      <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Rechercher un terme (ex. FERR, récupération, fractionnement)..." style={{ width: "100%", boxSizing: "border-box", background: C.cardBg, border: C.cardBorder, borderRadius: 12, padding: "12px 14px", color: C.text, fontSize: 14, outline: "none", marginBottom: 14 }} />
      <div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 18 }}>
        {["Toutes", ...CATS].map((c) => {
          const active = c === cat;
          return (<button key={c} onClick={() => setCat(c)} style={{ background: active ? C.goldBg : "transparent", border: active ? C.goldBorder : C.cardBorder, color: active ? C.gold : C.dim, borderRadius: 999, padding: "6px 14px", fontSize: 12.5, fontWeight: 600, cursor: "pointer" }}>{c}</button>);
        })}
      </div>
      <p style={{ fontSize: 12, color: C.faint, margin: "0 0 12px", fontFamily: C.mono }}>{filtres.length} terme{filtres.length > 1 ? "s" : ""}</p>
      {filtres.map((t) => (<TermCard key={t.terme} t={t} open={openKey === t.terme} onToggle={() => setOpenKey(openKey === t.terme ? null : t.terme)} />))}
      {filtres.length === 0 && (<p style={{ color: C.faint, fontSize: 14, marginTop: 24 }}>Aucun terme ne correspond à votre recherche.</p>)}
    </div>
  );
}
